  function renderGuide() {
    const sample = (title, description, options = {}) => `<article class="iw-guide-example"><div class="iw-guide-example-bar">${renderActionBadges({
      action: { skillName: 'Cooking', ...options.action }, masteryAchieved: false,
      cache: {}, locationBadges: '', ...options
    })}</div><h4>${title}</h4><p>${description}</p></article>`;
    const featureIcons = { 'Current Action': skillIcon('Cooking'), Crafting: skillIcon('Smithing'), 'Materials &amp; consumables': '/assets/misc/inventory.png', 'Current Loot': '/assets/misc/inventory.png', Potions: skillIcon('Alchemy'), Automations: skillIcon('Smelting'), 'Location &amp; idle': '/assets/icon.png' };
    const feature = (title, text) => {
      const key = title.split(':')[0];
      return `<article class="iw-guide-feature"><div class="iw-guide-feature-heading"><img src="${featureIcons[key] || '/assets/icon.png'}" alt=""><h4>${title}</h4></div><div class="iw-guide-feature-body">${text.startsWith('<p>') ? text : `<p>${text}</p>`}</div></article>`;
    };
    const chapter = (id, image, title, subtitle) => `<header class="iw-guide-chapter" id="iw-guide-${id}" data-guide-section="${id}" tabindex="-1"><img src="${image}" alt=""><div><h3>${title}</h3><p>${subtitle}</p></div></header>`;
    const rowGuide = (name, image, summary, body) => `<details class="iw-guide-row"><summary><img src="/assets/${image}" alt=""><span><b>${name}</b><small>${summary}</small></span></summary><div class="iw-guide-row-body">${body}</div></details>`;
    const indicator = (icon, text) => `<li>${icon}<span>${text}</span></li>`;
    const check = '<span class="iw-task-icon done" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M5 12.5l4 4L19 6.5"></path></svg></span>';
    const hourglass = '<span class="iw-task-icon participating" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M6 2h12M6 22h12M8 2v5l4 5-4 5v5M16 2v5l-4 5 4 5v5"></path></svg></span>';
    const idle = '<span class="iw-task-icon adventure-idle" aria-hidden="true"><span class="iw-idle-glyph">z<sup>Z</sup></span></span>';
    const event = state => guildEventStatusIcon({ schema: 9, state });
    const trial = state => guildTrialStatusIcon({ schema: 5, state });
    return `<div class="iw-modal" data-modal-backdrop><section class="iw-modal-panel iw-guide-panel" role="dialog" aria-modal="true" aria-labelledby="iw-guide-title">
      <div class="iw-options-heading"><img class="iw-guide-brand" src="/assets/icon.png" alt=""><div><h2 id="iw-guide-title">Status Guide</h2><small>Ironwood RPG · Dashboard &amp; automation</small></div><button class="iw-modal-close" data-modal-close aria-label="Close guide"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"></path></svg></button></div>
      <div class="iw-guide-body">
        <nav class="iw-guide-nav" aria-label="Guide chapters">${[['start','Start here'],['panels','Dashboard'],['icons','Indicators'],['rows','Status rows'],['data','Automation & data']].map(([id,label]) => `<button type="button" data-guide-jump="${id}" aria-controls="iw-guide-${id}">${label}</button>`).join('')}</nav>
        <section class="iw-guide-hero" aria-label="Dashboard introduction">
          <div class="iw-guide-intro"><span class="iw-guide-eyebrow">PLAYER HANDBOOK</span><h3>Your adventure.<br>One Status page.</h3><p>Follow your current action, collect rewards and see which supplies need attention.</p><div class="iw-guide-highlights"><span><img src="${skillIcon('Exploring')}" alt="">Activity</span><span><img src="/assets/misc/inventory.png" alt="">Rewards</span><span><img src="/assets/misc/quests.png" alt="">Daily progress</span></div></div>
          <div class="iw-guide-preview" aria-label="Illustrative dashboard example">
            <small class="iw-guide-preview-label">Example · frozen combat moment</small>
            <section class="iw-card iw-action-card iw-combat-card iw-guide-frozen-combat" style="--iw-recovery-icon:url('/assets/items/pie-king-crab.png')">
              <div class="iw-card-header"><span>Defense</span>${renderActionBadges({action:{isCombat:true,skillName:'Defense'},masteryAchieved:true,cache:{},locationBadges:selectLocationBadges({name:'Dungeon',isCombat:true},[{name:'Elite Key',image:'/assets/items/key-onyx.png'}],false).locationBadges})}</div>
              <div class="iw-action-body"><div class="iw-action-heading"><div class="iw-action-image"><img src="/assets/monsters/treant.png" alt=""></div><div class="iw-action-name"><span class="iw-action-title"><strong>Elite Treant</strong><small>(lvl 100)</small></span><span class="iw-action-meta"><span>Defense Lv. 110</span><span>66.8K XP/h</span><span>15% XP</span></span></div></div></div>
              ${renderCombatants({ isCombat: true, combatants: [
                { side: 'player', name: 'Player', image: '/assets/characters/character.png', hp: 840, maxHp: 1000, hpPercent: 84, meterPercent: 60, healAmount: 240 },
                { side: 'monster', name: 'Elite Treant', image: '/assets/monsters/treant.png', hp: 1140, maxHp: 1900, hpPercent: 60, meterPercent: 35, hit: true, lostPercent: 76 }
              ] }).replace(/ data-effect-times="[^"]*"/g, '')}
            </section>
            <section class="iw-card iw-activity-card"><div class="iw-card-header"><span>Status</span></div><div class="iw-status-list">
              <div class="iw-status-row"><img src="/assets/items/challenge-scroll.png" alt=""><span><b>Challenges</b><small class="iw-status-skill-details iw-challenge-details"><span class="iw-challenge-selection">${renderRegionIcon('Forest')}${renderStatusSkillIcon('Defense')}</span><span class="iw-challenge-scrolls"><img src="/assets/items/challenge-scroll.png" alt="Scrolls"><span>3</span></span></small></span><div class="iw-status-actions"><span class="iw-guide-claim-sample" title="Claim"><img src="/assets/misc/inventory.png" alt="Claim"></span></div></div>
              <div class="iw-status-row"><img src="/assets/misc/quests.png" alt=""><span><b>Daily quests</b><small class="iw-quest-progress"><img src="/assets/misc/quests.png" alt="Completed today"><span>5/5</span></small></span><div class="iw-status-actions">${check}</div></div>
            </div></section>
          </div>
        </section>
        <section>${chapter('start', '/assets/icon.png', 'Start here', 'Three steps to a useful dashboard.')}<ol class="iw-guide-steps"><li><b>Open Status</b><span>Find it above Inventory.</span></li><li><b>Browse normally</b><span>Visited pages fill saved values.</span></li><li><b>Set preferences</b><span>Use the sliders beside money.</span></li></ol></section>
        <section>${chapter('panels', '/assets/misc/inventory.png', 'Explore your dashboard', 'What each panel shows. Use the refresh icon in the Status panel’s title bar to reload cached data.')}<div class="iw-guide-features">
          ${feature('Current Action', '<b>XP/h</b> is your XP rate; <b>% XP</b> is progress toward the next level. Blue tracks the action cycle, green tracks skill XP. Combat shows HP and battle effects.')}
          ${feature('Crafting', 'Finish time, loot, total queued and inventory owned. The clock warns when your queue runs short.')}
          ${feature('Materials &amp; consumables', '<b>Available</b> shows materials; <b>Equipped</b> and <b>Stored</b> separate active supplies from reserves. Set low-supply alerts in Settings → Warnings.')}
          ${feature('Current Loot', '<b>Loot</b> is waiting to collect; <b>Inventory</b> is already stored. Coins are excluded from the item total. Claim requires automation.')}
          ${feature('Potions', 'Equipped potions and stored reserves. Choose which potion types appear in Settings → Potions.')}
          ${feature('Automations', 'House recipes, projected loot and work left in the queue. Visit House after changing a recipe or queue.')}
        </div></section>
        <section>${chapter('icons', '/assets/misc/mastery.png', 'Learn the indicators', 'Different shapes tell you what is happening; color adds context.')}<p>Dashboard badge examples. Warning thresholds below are defaults; change them in <b>Settings → Warnings</b>.</p><div class="iw-guide-examples">
          ${sample('Working steadily', 'Green spinner: action running.')}
          <article class="iw-guide-example"><div class="iw-guide-example-bar"><span class="iw-mastery-badge" aria-label="Mastery incomplete"><img src="/assets/misc/mastery.png" alt=""></span><span aria-hidden="true">→</span><span class="iw-mastery-badge achieved" aria-label="Mastery achieved"><img src="/assets/misc/mastery.png" alt=""></span></div><h4>Skill mastery</h4><p>Gray: incomplete. Gold: mastered.</p></article>
          ${sample('Plenty of crafting time', 'Green clock: at least 1 hour queued.', { queueWarning: 'sufficient', finiteQueue: { time: '2h' } })}
          ${sample('Queue running short', 'Amber: under 1 hour. Red: under 10 minutes.', { queueWarning: 'warning', finiteQueue: { time: '35m' } })}
          ${sample('Supplies need attention', 'Materials: amber below 1,000; red below 500.', { queueWarning: 'urgent', finiteQueue: { time: '5m' }, materialWarning: 'urgent', materialWarningText: 'Material low: Flour 240' })}
          ${sample('Bonuses that match your skill', 'Blue: matching adventure, event or trial bonus. Trials add 10% XP.', { adventureActionActive: true, guildEventActionActive: true, guildTrialActionActive: true, cache: { adventure: { mapName: 'Cooking Map' }, guildEvent: { eventName: 'Cooking event' }, guildTrial: { activeName: 'Cooking trial' } } })}
          ${sample('Combat &amp; revival', 'LIVE: combat. Red spinner and skull: reviving.', { action: { skillName: 'Defense', isCombat: true, reviveRemainingMs: 30000 } })}
          <article class="iw-guide-example"><div class="iw-guide-example-bar">${selectLocationBadges({location:'Village'}, [], false).locationBadges}${selectLocationBadges({location:'Outskirts'}, [], false).locationBadges}${selectLocationBadges({name:'Dungeon',isCombat:true}, [{name:'Elite Key',image:'/assets/items/key-onyx.png'}], false).locationBadges}</div><h4>Location</h4><p>Village · Outskirts · Dungeon</p></article>
        </div></section>
        <section>${chapter('rows', '/assets/misc/quests.png', 'Read the Status rows', 'Select a feature for its resources, controls and indicator states.')}<p>The icon on the left identifies the feature. The details show its progress or resources; the indicator or Claim button on the right tells you its current state. <b>A green check is specific to its row:</b> it can mean today’s work is finished, nothing more can be automated, or a trial is available to join.</p><p>Expand a row below for its exact meanings. These are examples, not your live values. On the dashboard, linked rows open their native game page; Daily quest choices are in Settings.</p><div class="iw-guide-rows">
          ${rowGuide('Challenges', 'items/challenge-scroll.png', 'Scrolls, selected region and reward skill', `<p>The region symbol and skill icon show your configured challenge region and XP reward skill. The scroll icon and its count stay together: <b>region | reward skill | scrolls + count</b>. Small dividers separate groups, not icons from their values.</p><ul class="iw-guide-indicators">${indicator(check, '<b>No further automatic starts available:</b> there are no scrolls and buying is off, or no auto-completes remain, with no active challenge waiting to be handled. This does not mean every challenge has been completed.')}${indicator(challengeBlockedIndicator(), '<b>Blocked:</b> the game says Cannot Auto or its auto-complete control is unavailable, and automatic cancellation is off. Review the challenge on its game page or enable cancellation in Settings.')}</ul><p><b>Claim</b> runs the configured challenge loop: use scrolls, auto-complete, select the reward skill and claim. Enabled buying and cancellation also apply. A spinner means the loop is working. The final recap shows confirmed totals, remaining auto-completes and why it stopped.</p>`)}
          ${rowGuide('Daily quests', 'misc/quests.png', 'Today’s completed quests, out of five', `<p><b>3/5</b> means three quests completed today, not three selected skills. Choose the five preferred skills in <b>Settings → Daily quests</b>.</p><ul class="iw-guide-indicators">${indicator(check, '<b>Today complete:</b> all five daily quests are done.')}</ul><p><b>Pending</b> means the saved daily progress is not complete. A spinner means the quest automation is processing. Enable automation and select all five skills for the automatic daily workflow; simply choosing skills does not mark quests complete.</p>`)}
          ${rowGuide('Adventure', 'misc/adventure.png', 'Running map, Research Points and daily map creation', `<p>The main line names a running map and its skill, with time left. The resource line groups each icon with its value: <b>RP + balance | maps + today / limit</b>. Creating maps and running an adventure are separate activities.</p><ul class="iw-guide-indicators">${indicator(hourglass, '<b>Adventure running:</b> the map’s countdown is active, even if you are training another skill.')}${indicator(idle, '<b>Ready to start:</b> no adventure is running and a stored map is available. Open Adventure to start one.')}${indicator(check, '<b>Daily map creation complete:</b> the daily creation target is finished. This check does not mean an adventure is running or finished.')}</ul><p>The active-adventure and ready-to-start indicators take priority over the daily check. An amber RP warning can appear beside any activity state; it warns about your balance, not that the adventure has stopped. The action-bar bonus appears only when your current skill matches the map.</p>`)}
          ${rowGuide('Taming', 'misc/taming.png', 'Expedition loot, Pet Snacks and ready eggs', `<p>The row names the selected expedition and shows your saved Pet Snack balance. <b>Claim</b> collects expedition loot; a spinner shows collection in progress and a green check briefly confirms it.</p><ul class="iw-guide-indicators">${indicator(renderTamingEggIndicator({ hatchery: true, ranch: true }), '<b>Eggs ready:</b> a yellow, gently shaking egg means the Hatchery or Ranch has eggs ready. Its tooltip identifies the source. Collection returns to your running skill before reopening Status. Open Taming to handle them; the loot Claim button does not hatch eggs.')}</ul>`)}
          ${rowGuide('Attunement', 'misc/attunement.png', 'Regional Tribute balances and selected skills', `<p>Each line reads <b>region | selected skill | Tribute balance</b>. The numbers align in a column; dividers separate the three parts. These are Tribute amounts, not the amount of loot waiting to be claimed. Balances remain visible for regions without a selected skill.</p><p><b>Claim</b> collects available Attunement loot across selected slots. An amber balance or warning means a known Tribute amount is below your configured threshold. The warning does not replace the Claim button or mean that every slot has stopped. Open Attunement to change skills or review a low balance.</p><p>After Claim, each skill gets a compact recap header with its XP icon and amount, followed by item rewards and any shards. There is no overall XP or slot-count row. Confirmed rewards remain in the recap if a later slot fails. The main game synchronizes before the recap appears, so opening Attunement does not require a manual refresh.</p>`)}
          ${rowGuide('Guild event', 'misc/combat.png', 'Your contribution, the event deadline or the next cooldown', `<p>The event-type icon identifies Gathering, Crafting or Combat. During participation, the row shows your contribution XP and remaining participation time.</p><ul class="iw-guide-indicators">${indicator(event('Available'), '<b>Green hourglass — available:</b> the event can be started; you are not shown as participating.')}${indicator(event('Participating'), '<b>Blue hourglass — participating:</b> your contribution timer is still active.')}${indicator(event('Completed'), '<b>Green check — contribution complete:</b> your participant row no longer has a timer. The remaining countdown now belongs to the overall event. The matching action bonus disappears because your contribution time is over.')}${indicator(event('Cooldown'), '<b>Amber hourglass — cooldown:</b> the row shows time until the next event can start, with an arrow pointing to its type.')}</ul><p>Gray means unavailable; a dashed gray hourglass means participation needs checking. Open <b>Guild → Events</b> to refresh it. An event being active for your guild is not enough to activate your action bonus: you must still be participating and training a matching skill.</p>`)}
          ${rowGuide('Guild trials', 'misc/quests.png', 'Your trial participation and trials available to join', `<p>A running trial shows its name and your participation countdown. The overall guild trial period has its own deadline. “About” means the game supplied a rounded time, so the countdown is an estimate.</p><ul class="iw-guide-indicators">${indicator(trial('Active'), '<b>Blue hourglass — participating:</b> your trial is running. Its action-bar bonus appears only for the matching skill.')}${indicator(trial('Available'), '<b>Green check — available or completed:</b> read the row’s text. “Trials available” means you can join; “Completed” means the trial is finished. The check alone does not mean you are participating.')}${indicator(trial('Expired'), '<b>Amber hourglass — participation ended:</b> your observed personal timer has expired. Open Trials to check the next state.')}</ul><p>Gray means unavailable; dashed gray means your participation has not been checked. Open <b>Guild → Trials</b> to refresh it.</p>`)}
        </div><p>A disabled Claim button can mean automation is off, no eligible reward or task is known, or an action is already being processed. A warning about RP or Tribute is separate from whether an activity is running.</p></section>
        <section class="iw-guide-note">${chapter('data', '/assets/misc/inventory.png', 'Automation &amp; saved data', 'You decide what runs and when the game is checked.')}<p><b>Automation and fallback lookups start off.</b> Automation enables game-changing tasks and Claim buttons. Fallback lookups allow background reads when usable information is missing. You can still populate the dashboard by visiting pages yourself.</p><div class="iw-guide-permissions"><div><b>Claim buttons</b><span>Enable automation</span></div><div><b>Daily quests &amp; map creation</b><span>Automation + fallback lookups</span></div><div><b>Saved values &amp; local timers</b><span>No automation required</span></div></div><p>Daily quests also need exactly five chosen skills. Map creation keeps Legendary maps and sells other rarities; it does not start an adventure. Both workflows stop when today’s work is complete.</p><p>Challenge cancellation and buying entries are separate options. Cancellation does not refund spent resources. Buying spends gold with doubling prices; the selected maximum is a <b>per-entry limit</b>, not a total budget.</p></section>
        <section><h3>Fresh information, clear expectations</h3><p>Current activity comes from the game interface. Other panels use saved snapshots, with known countdowns and production calculated locally. A snapshot’s age tells you when it was read; it does not mean the game was just checked. Open the native page to update it. Confirmed loot additions and material use update saved counts locally. After a challenge run or Attunement claim, the main game’s inventory, gold and timers synchronize before its recap appears; a synchronization failure is shown separately from the confirmed totals.</p><p>Settings → Warnings lets you change queue, material, Research Point and Tribute warning levels; zero disables a warning. “About” on a timer means the source time was rounded or estimated. A compact quantity such as 12.1K can still have an exact underlying count; if the game only supplied a rounded count, Status preserves that uncertainty instead of inventing precision. Green and red quantity changes show increases and decreases. If something looks missing, visit that feature’s page; Settings → Debug can show saved values and recent refresh activity.</p></section>
      </div><footer><button class="iw-small-button iw-options-done" data-modal-close>Got it</button></footer>
    </section></div>`;
  }

  function navigateGuideSection(id) {
    const panel = document.querySelector('.iw-guide-panel');
    const heading = [...(panel?.querySelectorAll('[data-guide-section]') || [])]
      .find(element => element.dataset.guideSection === id);
    if (!heading) return;
    heading.scrollIntoView({ block: 'start', behavior: 'instant' });
    heading.focus({ preventScroll: true });
  }
