  function renderShoppingCard() {
    if (location.pathname !== '/status') return '';
    const ui = AppState.ui.shopping, runtime = quickRuntime(), snapshot = ui.snapshot;
    const amount = value => value === null ? 'Unknown' : formatNumber(value);
    const draft = ui.draft;
    const index = shoppingRecipes(runtime);
    const items = Object.values(runtime?.catalog || {}).filter(item => shoppingItem(runtime, item?.id) && index.craftableItems.has(item.id) && (item.id === draft.itemId || item.name.toLowerCase().includes(ui.filter.toLowerCase()))).sort((a, b) => a.name.localeCompare(b.name));
    const choices = (index.byItem.get(draft.itemId) || []);
    const invalidated = ui.plan?.itemId === draft.itemId && ui.plan.recipeKey && !choices.some(entry => entry.key === ui.plan.recipeKey);
    return `<section class="iw-card iw-shopping-card" aria-label="Finished-item shopping list"><div class="iw-card-header"><span>Shopping list</span><div class="iw-shopping-actions"><button type="button" class="iw-small-button" data-shopping-refresh ${!ui.owner || ui.refreshing || quickBusy() || shoppingPending(runtime) ? 'disabled' : ''}>${ui.refreshing ? 'Refreshing…' : 'Refresh'}</button>${ui.plan ? '<button type="button" class="iw-small-button" data-shopping-edit>Edit</button><button type="button" class="iw-small-button" data-shopping-clear>Clear</button>' : ''}</div></div><div class="iw-shopping-body">
      ${!ui.owner ? '<p>Character identity unavailable.</p>' : ui.editing ? `<form data-shopping-form data-shopping-owner="${escapeHtml(ui.owner)}">
        <label>Filter items<input type="search" data-shopping-filter value="${escapeHtml(ui.filter)}"></label><label>Finished item<select name="item" required data-shopping-item><option value="">Choose an item</option>${items.map(item => `<option value="${item.id}" ${item.id === draft.itemId ? 'selected' : ''}>${escapeHtml(item.name)}</option>`).join('')}</select></label>
        <label>Target owned quantity<input name="quantity" data-shopping-quantity type="number" min="1" step="1" required value="${escapeHtml(draft.quantity)}"></label>
        ${choices.length > 1 || invalidated ? `<label>Crafting recipe<select name="recipe" data-shopping-recipe><option value="">Choose a recipe</option>${choices.map(entry => `<option value="${entry.key}" ${entry.key === draft.recipeKey ? 'selected' : ''}>${escapeHtml(entry.skillName)} · ${escapeHtml(entry.recipe.name)}</option>`).join('')}</select></label>` : choices.length === 1 ? `<span>Crafted with ${escapeHtml(choices[0].skillName)} · ${escapeHtml(choices[0].recipe.name)}</span>` : ''}<button class="iw-small-button" type="submit">Save target</button>${ui.plan ? '<button type="button" class="iw-small-button" data-shopping-cancel>Cancel</button>' : ''}</form>` : ''}
      ${snapshot ? `${ui.unavailable ? '<p role="status">Last observation; current balances unavailable. Refresh when synchronization or collection finishes.</p>' : ''}<p><strong>${escapeHtml(snapshot.name)}</strong> · Target owned quantity ${amount(ui.plan.quantity)} · Owned ${amount(snapshot.owned)} · <strong>${snapshot.shortfall === 0 ? 'Target satisfied' : `${amount(snapshot.shortfall)} to acquire`}</strong></p>
        ${snapshot.gaps.map(gap => `<p>${escapeHtml(gap)}</p>`).join('')}
        ${snapshot.chosen ? `<p>${escapeHtml(snapshot.eligibility)}</p><p>${escapeHtml(snapshot.yieldText)}</p><p>${snapshot.attempts === null ? 'Attempt count unknown' : `${amount(snapshot.attempts)} ${snapshot.fixed ? 'base' : 'nominal'} attempts · ${amount(snapshot.output)} ${snapshot.fixed ? 'base' : 'nominal'} output`}</p>
        <p>${snapshot.rows.filter(row => row.missing !== 0).map(row => `${amount(row.missing)} ${escapeHtml(row.name)}${row.special ? ' (native balance)' : ''}`).join(' · ') || (snapshot.fixed && !snapshot.gaps.length && !ui.unavailable ? 'Base materials covered; finished items have not been crafted.' : 'Known inputs covered; complete material coverage is unconfirmed.')}</p>
        <details data-shopping-details ${ui.expanded ? 'open' : ''}><summary>Direct recipe detail</summary><table><thead><tr><th>Ingredient</th><th>Per attempt</th><th>Required</th><th>Owned</th><th>Missing</th></tr></thead><tbody>${snapshot.rows.map(row => `<tr><th>${escapeHtml(row.name)}${row.special ? '<small>Native balance</small>' : row.intermediate ? '<small>Intermediate item to acquire</small>' : ''}</th>${[['Per attempt', row.perAttempt], ['Required', row.required], ['Owned', row.owned], ['Missing', row.missing]].map(([label, value]) => `<td data-label="${label}">${amount(value)}</td>`).join('')}</tr>`).join('')}</tbody></table><a href="/skill/${snapshot.chosen.skillId}/action/${snapshot.chosen.recipe.id}">Open native recipe</a></details>` : ''}
        <p class="iw-muted">Observed ${Math.max(0, Math.floor((Date.now() - snapshot.observedAt) / 60000))} min ago.</p>` : ''}
      <p class="iw-muted">Direct ingredients only. Owned stock only; excludes pending loot, queues, preservation savings and bonus output.</p>${ui.message ? `<p role="status">${escapeHtml(ui.message)}</p>` : ''}</div></section>`;
  }
