  function createAppState() {
    return {
      live: { action: null, loot: [], consumables: [], materials: [], combatants: [], observations: {},
        lastCombatAction: null,
        lastCombatSeenAt: 0,
        previousLootValues: new Map(),
        previousConsumableValues: new Map(),
        previousMaterialValues: new Map(),
        reviveUntil: 0,
        lastReviveObservedMs: 0
      },
      cache: { schemaVersion: 2, records: {} },
      derived: { automationRows: [], displayedPotions: [], countdowns: {} },
      ui: { activeRoute: '/', pendingActions: new Map(), events: new Map(),
        previousUrl: '/',
        hiddenRouteElements: [],
        lastSignature: '',
        cacheRevision: 0,
        cacheWrites: {},
        lookupActivity: [],
        actionToasts: [],
        toastSequence: 0,
        startupSyncAt: null,
        quantityPrecision: { installed: false, lastAttemptAt: null },
        debugPanel: null,
        debugUpdatedAt: 0,
        renderFrame: null,
        lootDeltaNotices: new Map(),
        consumableDeltaNotices: new Map(),
        materialDeltaNotices: new Map(),
        combatEffects: new Map(),
        combatEffectLockUntil: 0,
        combatUseNotice: null,
        combatDropNotice: null,
        eliteCombatDetected: false,
        questModalOpen: false,
        guideOpen: false,
        questOptionsExpanded: false,
        headerSnapshot: null,
        headerBadgeMarkup: '',
        headerActionSnapshot: null,
        preferencesTrigger: null,
        collectingLoot: false,
        pendingLootClaim: null,
        lastAdventureCapture: 0,
        visibleCaptureTimes: {},
        refreshingAdventure: false,
        refreshingChallenges: false,
        refreshingTaming: false,
        refreshingAutomations: false,
        automationTask: '',
        collectingAttunementLoot: false,
        runningChallenge: false,
        collectingTaming: false,
        collectingAutomation: '',
        tamingClaimNoticeUntil: 0,
        syncing: false,
        page: null,
        navButton: null
      }
    };
  }
  const AppState = createAppState();
