  function renderAutomationsPanel(automationRows, cache, automationOn) {
    return `        <section class="iw-card iw-automations-card">
          <div class="iw-card-header"><span>Automations</span><div class="iw-summary"><small>${AppState.ui.refreshingAutomations ? 'Updating…' : humanAge(cache.automations?.checkedAt)}</small>${AppState.ui.collectingAutomation || automationRows.some((item) => item.lootAmount > 0) ? `<button class="iw-collect-button iw-claim-button" data-collect-automations data-claim-state="${AppState.ui.collectingAutomation ? 'busy' : 'ready'}" ${automationOn && !AppState.ui.collectingAutomation && !AppState.ui.refreshingAutomations ? '' : 'disabled'} title="${automationOn ? 'Claim all automation loot' : 'Automation is disabled'}">${AppState.ui.collectingAutomation ? 'Claiming…' : 'Claim'}</button>` : ''}</div></div>
          ${cache.automations?.lastError ? `<div class="iw-muted" role="alert">${escapeHtml(cache.automations.lastError)}</div>` : ''}
          ${automationRows.length ? `<div class="iw-data-table iw-automation-table">
            <div class="iw-table-head"><span>Structure</span><span>Making</span><span>Loot</span><span>Queued</span></div>
            ${automationRows.map((item, index) => `<div class="iw-table-row">
              <div class="iw-automation-heading"><div class="iw-automation-label iw-automation-structure" title="${escapeHtml(item.structure)}"><img src="${escapeHtml(item.image)}" alt=""><span>${escapeHtml(item.structure)}</span></div>
              <div class="iw-automation-label iw-automation-recipe" title="${escapeHtml(item.making || 'Idle')}">${item.makingImage ? `<img src="${escapeHtml(item.makingImage)}" alt="">` : '<span class="iw-zero iw-automation-placeholder">—</span>'}<span>${escapeHtml(item.making || 'Idle')}</span></div></div>
              <div class="iw-automation-metrics"><div class="iw-automation-duration" title="Approximate time remaining"><span data-live-automation-time="${index}">${automationRemainingTime(item, cache.automations?.checkedAt)}</span><svg viewBox="0 0 24 24" role="img" aria-label="Time remaining"><circle cx="12" cy="12" r="8"></circle><path d="M12 7v5l3 2"></path></svg></div><div class="iw-automation-completed" title="Actions completed"><span data-live-automation-done="${index}">${formatNumber(item.queuedDone || 0)}</span><svg viewBox="0 0 24 24" role="img" aria-label="Completed"><path d="m5 12 4 4L19 6"></path></svg></div><div class="iw-automation-value ${item.lootAmount ? '' : 'iw-zero'}" title="Loot ready to collect: ${escapeHtml(item.lootName || 'Loot')}" data-label="Loot"><img class="iw-automation-metric-icon" src="/assets/misc/inventory.png" alt="Loot"><span data-live-automation-loot="${index}">${item.lootAmount ? formatNumber(item.lootAmount) : '0'}</span></div>
              <div class="iw-table-number ${item.queuedTotal > item.queuedDone ? '' : 'iw-zero'}" data-label="Queued" title="Total queue"><svg class="iw-automation-metric-icon" viewBox="0 0 24 24" role="img" aria-label="Queued"><path d="m12 3 9 5-9 5-9-5 9-5Zm-9 9 9 5 9-5M3 16l9 5 9-5"></path></svg><span data-live-automation-queue="${index}">${formatNumber(item.queuedTotal || 0)}</span></div></div>
            </div>`).join('')}
          </div>` : `<div class="iw-muted">${AppState.ui.refreshingAutomations ? 'Reading structures…' : 'Automation data has not been loaded yet.'}</div>`}
        </section>`;
  }
